package com.sample.dbmodel;

import java.util.List;
import org.apache.ibatis.annotations.Mapper;

/**
 * Mapper interface for todo.
 * Generated by MyBateans.
 */
@Mapper
public interface TodoMapper {

    /**
     * Select records by example.
     */
    List<Todo> select(Todo example);

    /**
     * Insert a new record.
     */
    int insert(Todo record);

    /**
     * Update records by example.
     */
    int update(Todo record);

    /**
     * Delete records by example.
     */
    int delete(Todo example);
}