
package com.jhappy.mybateans.wizard.mapperxml;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class MyBatisMapperXmlVisualPanel1 extends JPanel {

    /**
     * Creates new form MyBatisMapperXmlVisualPanel1
     */
    public MyBatisMapperXmlVisualPanel1() {
        initComponents();

        txtfTableName.getDocument().addDocumentListener(new DocumentListener() {
            private void update() {
                String table = txtfTableName.getText();

                String className = toClassName(table);
                String fileName = className + "Mapper";

                txtfFileName.setText(fileName);
                txtfClassName.setText(fileName);
                txtfResultType.setText(className);

            }

            public void insertUpdate(DocumentEvent e) {
                update();
            }

            public void removeUpdate(DocumentEvent e) {
                update();
            }

            public void changedUpdate(DocumentEvent e) {
                update();
            }
        });
    }

    public static String toClassName(String tableName) {
        String[] parts = tableName.split("_");
        StringBuilder sb = new StringBuilder();

        for (String p : parts) {
            if (p.isEmpty()) {
                continue;
            }
            sb.append(Character.toUpperCase(p.charAt(0)));
            sb.append(p.substring(1).toLowerCase());
        }

        return sb.toString();
    }

    @Override
    public String getName() {
        return "Step #1";
    }

    public String getTableName() {
        return txtfTableName.getText();
    }

    public String getNamespace() {
        return txtfNamespace.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfFileName = new javax.swing.JTextField();
        lblFileName = new javax.swing.JLabel();
        lblNamespace = new javax.swing.JLabel();
        txtfNamespace = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtfTableName = new javax.swing.JTextField();
        lblTableName = new javax.swing.JLabel();
        txtfClassName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblResultType = new javax.swing.JLabel();
        txtfResultType = new javax.swing.JTextField();
        lblText1 = new javax.swing.JLabel();

        txtfFileName.setText(org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.txtfFileName.text")); // NOI18N
        txtfFileName.setEnabled(false);
        txtfFileName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfFileNameActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblFileName, org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.lblFileName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblNamespace, org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.lblNamespace.text")); // NOI18N

        txtfNamespace.setText(org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.txtfNamespace.text")); // NOI18N
        txtfNamespace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfNamespaceActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.jLabel1.text")); // NOI18N

        txtfTableName.setText(org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.txtfTableName.text")); // NOI18N
        txtfTableName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfTableNameActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(lblTableName, org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.lblTableName.text")); // NOI18N

        txtfClassName.setText(org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.txtfClassName.text")); // NOI18N
        txtfClassName.setEnabled(false);
        txtfClassName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfClassNameActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblResultType, org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.lblResultType.text")); // NOI18N

        txtfResultType.setText(org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.txtfResultType.text")); // NOI18N
        txtfResultType.setEnabled(false);

        org.openide.awt.Mnemonics.setLocalizedText(lblText1, org.openide.util.NbBundle.getMessage(MyBatisMapperXmlVisualPanel1.class, "MyBatisMapperXmlVisualPanel1.lblText1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblText1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                    .addComponent(txtfResultType, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtfTableName, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtfFileName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtfNamespace, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtfClassName))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTableName)
                            .addComponent(lblNamespace)
                            .addComponent(lblFileName)
                            .addComponent(lblResultType))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTableName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfTableName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFileName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtfFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(lblNamespace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfNamespace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfClassName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(lblResultType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtfResultType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblText1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtfFileNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfFileNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfFileNameActionPerformed

    private void txtfNamespaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfNamespaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfNamespaceActionPerformed

    private void txtfTableNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfTableNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfTableNameActionPerformed

    private void txtfClassNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfClassNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfClassNameActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFileName;
    private javax.swing.JLabel lblNamespace;
    private javax.swing.JLabel lblResultType;
    private javax.swing.JLabel lblTableName;
    private javax.swing.JLabel lblText1;
    public javax.swing.JTextField txtfClassName;
    public javax.swing.JTextField txtfFileName;
    public javax.swing.JTextField txtfNamespace;
    private javax.swing.JTextField txtfResultType;
    public javax.swing.JTextField txtfTableName;
    // End of variables declaration//GEN-END:variables
}
