<#assign licenseFirst = "/*">
<#assign licensePrefix = " * ">
<#assign licenseLast = " */">
<#if package?? && package != "">
package ${package};
</#if>

<#if isUseJpaAnnotation>
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;
</#if>

/**
 * Data Model for table: ${classname}
 * Generated by MyBateans
 */
 <#if isUseJpaAnnotation>
@Entity
</#if>
public class ${classname} {

<#-- Generate Field -->
<#list cols as col>
    <#-- Convert Type From DB Type -->
    <#assign javaType = "String">
    <#if col.TYPE_NAME == "INTEGER" || col.TYPE_NAME == "INT" || col.TYPE_NAME == "INT UNSIGNED">
        <#assign javaType = "Integer">
    <#elseif col.TYPE_NAME == "BIGINT" || col.TYPE_NAME == "BIGINT UNSIGNED">
        <#assign javaType = "Long">
    <#elseif col.TYPE_NAME == "DECIMAL" || col.TYPE_NAME == "NUMERIC">
        <#assign javaType = "java.math.BigDecimal">
    <#elseif col.TYPE_NAME?contains("DATE") || col.TYPE_NAME?contains("TIME") || col.TYPE_NAME?contains("TIMESTAMP")>
        <#assign javaType = "java.util.Date">
    <#elseif col.TYPE_NAME == "BOOLEAN" || col.TYPE_NAME == "BIT">
        <#assign javaType = "Boolean">
    </#if>
    
    <#if isUseJpaAnnotation>
    <#if col.IS_KEY == true>
    @Id
    </#if>
    @Column(name = "${col.COLUMN_NAME}")
    </#if>
    private ${javaType} ${col.COLUMN_NAME_LOWER_CAMEL_CASE}; <#if col.IS_KEY == true> // Primary Key </#if>
</#list>

    public ${classname}() {
    }

<#-- Generate Getter/Setter -->
<#list cols as col>
    <#assign javaType = "String">
    <#if col.TYPE_NAME == "INTEGER" || col.TYPE_NAME == "INT" || col.TYPE_NAME == "INT UNSIGNED">
        <#assign javaType = "Integer">
    <#elseif col.TYPE_NAME == "BIGINT" || col.TYPE_NAME == "BIGINT UNSIGNED">
        <#assign javaType = "Long">
    <#elseif col.TYPE_NAME == "DECIMAL" || col.TYPE_NAME == "NUMERIC">
        <#assign javaType = "java.math.BigDecimal">
    <#elseif col.TYPE_NAME?contains("DATE") || col.TYPE_NAME?contains("TIME") || col.TYPE_NAME?contains("TIMESTAMP")>
        <#assign javaType = "java.util.Date">
    <#elseif col.TYPE_NAME == "BOOLEAN" || col.TYPE_NAME == "BIT">
        <#assign javaType = "Boolean">
    </#if>
    
    <#assign methodName = col.COLUMN_NAME_LOWER_CAMEL_CASE?cap_first>

    public ${javaType} get${methodName}() {
        return this.${col.COLUMN_NAME_LOWER_CAMEL_CASE};
    }

    public void set${methodName}(${javaType} ${col.COLUMN_NAME_LOWER_CAMEL_CASE}) {
        this.${col.COLUMN_NAME_LOWER_CAMEL_CASE} = ${col.COLUMN_NAME_LOWER_CAMEL_CASE};
    }

</#list>
}