<#--

 * This template is invoked by either the "MyBateans DB Model File Wizard" 
 * or the "Generate JavaBean" action from the Database Explorer context menu.
 * * When invoked from the Database Explorer:
 * - 'isUseJpaAnnotation' is always false.
 * - 'package' is always null.

 * @parameter package             [String]  Target package name for the generated class (e.g., com.example.model). 
 * (Note: Always null when invoked from Database Explorer)
 * @parameter classname           [String]  Generated Java class name (e.g., UserInfo).
 * @parameter tableName           [String]  Source database table name (e.g., USER_INFO).
 * @parameter isUseJpaAnnotation  [Boolean] Flag to determine whether to output JPA annotations. 
 * (Note: Always false when invoked from Database Explorer)
 * @parameter cols                [List]    List of column metadata. Each element is a Map containing:
 * - COLUMN_NAME                  [String]  Original column name in the database.
 * - TYPE_NAME                    [String]  SQL type name (e.g., VARCHAR, INTEGER).
 * - COLUMN_NAME_LOWER_CAMEL_CASE [String]  Converted variable name in lowerCamelCase.
 * - COLUMN_SIZE                  [Integer] Column size
 * - IS_KEY                       [Boolean] Boolean flag indicating if the column is a Primary Key.

-->
<#assign licenseFirst = "/*">
<#assign licensePrefix = " * ">
<#assign licenseLast = " */">
<#if package?? && package != "">
package ${package};
</#if>

<#if isUseJpaAnnotation>
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Column;
</#if>

/**
 * Data Model for table: ${tableName}
 * Generated by MyBateans
 */
 <#if isUseJpaAnnotation>
@Entity
</#if>
public class ${classname} {

<#-- Generate Field -->
<#list cols as col>
    <#-- Convert Type From DB Type -->
    <#assign javaType = "String">
    <#if col.TYPE_NAME == "INTEGER" || col.TYPE_NAME == "INT" || col.TYPE_NAME == "INT UNSIGNED">
        <#assign javaType = "Integer">
    <#elseif col.TYPE_NAME == "BIGINT" || col.TYPE_NAME == "BIGINT UNSIGNED">
        <#assign javaType = "Long">
    <#elseif col.TYPE_NAME == "DECIMAL" || col.TYPE_NAME == "NUMERIC">
        <#assign javaType = "java.math.BigDecimal">
    <#elseif col.TYPE_NAME?contains("DATE") || col.TYPE_NAME?contains("TIME") || col.TYPE_NAME?contains("TIMESTAMP")>
        <#assign javaType = "java.util.Date">
    <#elseif col.TYPE_NAME == "BOOLEAN" || col.TYPE_NAME == "BIT">
        <#assign javaType = "Boolean">
    </#if>
    
    <#if isUseJpaAnnotation>
    <#if col.IS_KEY == true>
    @Id
    </#if>
    @Column(name = "${col.COLUMN_NAME}")
    </#if>
    private ${javaType} ${col.COLUMN_NAME_LOWER_CAMEL_CASE}; <#if col.IS_KEY == true> // Primary Key </#if>
</#list>

    public ${classname}() {
    }

<#-- Generate Getter/Setter -->
<#list cols as col>
    <#assign javaType = "String">
    <#if col.TYPE_NAME == "INTEGER" || col.TYPE_NAME == "INT" || col.TYPE_NAME == "INT UNSIGNED">
        <#assign javaType = "Integer">
    <#elseif col.TYPE_NAME == "BIGINT" || col.TYPE_NAME == "BIGINT UNSIGNED">
        <#assign javaType = "Long">
    <#elseif col.TYPE_NAME == "DECIMAL" || col.TYPE_NAME == "NUMERIC">
        <#assign javaType = "java.math.BigDecimal">
    <#elseif col.TYPE_NAME?contains("DATE") || col.TYPE_NAME?contains("TIME") || col.TYPE_NAME?contains("TIMESTAMP")>
        <#assign javaType = "java.util.Date">
    <#elseif col.TYPE_NAME == "BOOLEAN" || col.TYPE_NAME == "BIT">
        <#assign javaType = "Boolean">
    </#if>
    
    <#assign methodName = col.COLUMN_NAME_LOWER_CAMEL_CASE?cap_first>

    public ${javaType} get${methodName}() {
        return this.${col.COLUMN_NAME_LOWER_CAMEL_CASE};
    }

    public void set${methodName}(${javaType} ${col.COLUMN_NAME_LOWER_CAMEL_CASE}) {
        this.${col.COLUMN_NAME_LOWER_CAMEL_CASE} = ${col.COLUMN_NAME_LOWER_CAMEL_CASE};
    }

</#list>
}