<#ftl strip_whitespace=false>
package ${packageName};

import java.util.List;
import org.apache.ibatis.annotations.Mapper;

/**
 * Mapper interface for ${tableName}.
 * Generated by MyBateans.
 */
@Mapper
public interface ${className}Mapper {

    /**
     * Select records by example.
     */
    List<${className}> select(${className} example);

    /**
     * Insert a new record.
     */
    int insert(${className} record);

    /**
     * Update records by example.
     */
    int update(${className} record);

    /**
     * Delete records by example.
     */
    int delete(${className} example);
}