package com.jhappy.mybateans.wizard.configxml;

import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.openide.util.ImageUtilities;

public final class MyBatisConfigXmlVisualPanel2 extends JPanel {

    /**
     */
    public MyBatisConfigXmlVisualPanel2() {
        initComponents();

        final Map<String, String> DRIVER_URL_MAP = new LinkedHashMap<>();

        DRIVER_URL_MAP.put("com.mysql.cj.jdbc.Driver", "jdbc:mysql://localhost:3306/dbname?serverTimezone=UTC");
        DRIVER_URL_MAP.put("com.mysql.jdbc.Driver", "jdbc:mysql://localhost:3306/dbname");

        // PostgreSQL
        DRIVER_URL_MAP.put("org.postgresql.Driver", "jdbc:postgresql://localhost:5432/dbname");

        // Oracle
        DRIVER_URL_MAP.put("oracle.jdbc.driver.OracleDriver", "jdbc:oracle:thin:@localhost:1521:xe");

        // SQL Server
        DRIVER_URL_MAP.put("com.microsoft.sqlserver.jdbc.SQLServerDriver", "jdbc:sqlserver://localhost:1433;databaseName=dbname;encrypt=true;trustServerCertificate=true");

        // H2 (メモリ & ファイル)
        DRIVER_URL_MAP.put("org.h2.Driver", "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1");

        // Apache Derby (Network & Embedded)
        DRIVER_URL_MAP.put("org.apache.derby.client.ClientAutoloadedDriver", "jdbc:derby://localhost:1527/dbname");
        DRIVER_URL_MAP.put("org.apache.derby.jdbc.ClientDriver", "jdbc:derby://localhost:1527/dbname");
        DRIVER_URL_MAP.put("org.apache.derby.iapi.jdbc.AutoloadedDriver", "jdbc:derby:dbname;create=true");

        // SQLite
        DRIVER_URL_MAP.put("org.sqlite.JDBC", "jdbc:sqlite:sample.db");

        // MariaDB
        DRIVER_URL_MAP.put("org.mariadb.jdbc.Driver", "jdbc:mariadb://localhost:3306/dbname");

        java.awt.Image image = ImageUtilities.loadImage("com/jhappy/mybateans/wizard/configxml/descriptionaboutjndi.png");
        if (image != null) {
            lblDescriptionImage.setIcon(new ImageIcon(image));
        } else {
            lblDescriptionImage.setText("No Image");
        }
        
        cmbDriver.addItemListener(new ItemListener(){
            @Override
            public void itemStateChanged(ItemEvent e) {
                txtUrlSample.setText(DRIVER_URL_MAP.get((String)e.getItem()));
            }
        });

    }

    public void updateLayout(String dataSourceType) {
        CardLayout cardLayout = (CardLayout) getLayout();
        if ("JNDI".equals(dataSourceType)) {
            cardLayout.show(this, "card4");
        } else {
            cardLayout.show(this, "card2");
        }

    }

    @Override
    public String getName() {
        return "Step #1";
    }

    public String getJdbcDriver() {
        return (String) cmbDriver.getSelectedItem();
    }

    public String getJdbcUrl() {
        return (String) txtUrl.getText();
    }

    public String getJndi() {
        return (String) txtJndi.getText();
    }

    public String getUser() {
        return (String) txtUser.getText();
    }

    public String getPassword() {
        return (String) txtPassword.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJdbc = new javax.swing.JPanel();
        lblDriver = new javax.swing.JLabel();
        cmbDriver = new javax.swing.JComboBox<>();
        lblUrl = new javax.swing.JLabel();
        txtUrl = new javax.swing.JTextField();
        lblUrlSample = new javax.swing.JLabel();
        txtUrlSample = new javax.swing.JTextField();
        lblUser = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        pnlJndi = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtJndi = new javax.swing.JTextField();
        lblDescriptionImage = new javax.swing.JLabel();
        lblJndiDesctiption = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        lblDriver.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblDriver, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.lblDriver.text")); // NOI18N

        cmbDriver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "org.apache.derby.jdbc.ClientDriver", "org.h2.Driver", "org.sqlite.JDBC", "com.mysql.jdbc.Driver", "com.mysql.cj.jdbc.Driver", "org.postgresql.Driver", "oracle.jdbc.driver.OracleDriver", "com.microsoft.sqlserver.jdbc.SQLServerDriver", "org.apache.derby.client.ClientAutoloadedDriver", "org.mariadb.jdbc.Driver" }));

        lblUrl.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblUrl, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.lblUrl.text")); // NOI18N

        txtUrl.setText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.txtUrl.text")); // NOI18N
        txtUrl.setToolTipText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.txtUrl.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblUrlSample, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.lblUrlSample.text")); // NOI18N

        txtUrlSample.setBackground(java.awt.SystemColor.window);
        txtUrlSample.setText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.txtUrlSample.text")); // NOI18N
        txtUrlSample.setToolTipText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.txtUrlSample.toolTipText")); // NOI18N
        txtUrlSample.setBorder(null);
        txtUrlSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUrlSampleActionPerformed(evt);
            }
        });

        lblUser.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblUser, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.lblUser.text")); // NOI18N

        txtUser.setText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.txtUser.text")); // NOI18N

        lblPassword.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblPassword, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.lblPassword.text")); // NOI18N

        txtPassword.setText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.txtPassword.text")); // NOI18N

        javax.swing.GroupLayout pnlJdbcLayout = new javax.swing.GroupLayout(pnlJdbc);
        pnlJdbc.setLayout(pnlJdbcLayout);
        pnlJdbcLayout.setHorizontalGroup(
            pnlJdbcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJdbcLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJdbcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUrl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbDriver, 0, 446, Short.MAX_VALUE)
                    .addComponent(txtUrlSample)
                    .addComponent(txtUser)
                    .addGroup(pnlJdbcLayout.createSequentialGroup()
                        .addGroup(pnlJdbcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDriver)
                            .addComponent(lblUrl)
                            .addComponent(lblUrlSample)
                            .addComponent(lblUser)
                            .addComponent(lblPassword))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtPassword))
                .addContainerGap())
        );
        pnlJdbcLayout.setVerticalGroup(
            pnlJdbcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJdbcLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(lblUrl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblUrlSample)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrlSample, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        add(pnlJdbc, "card2");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.jLabel1.text")); // NOI18N

        txtJndi.setText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.txtJndi.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblDescriptionImage, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.lblDescriptionImage.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(lblJndiDesctiption, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel2.class, "MyBatisConfigXmlVisualPanel2.lblJndiDesctiption.text")); // NOI18N

        javax.swing.GroupLayout pnlJndiLayout = new javax.swing.GroupLayout(pnlJndi);
        pnlJndi.setLayout(pnlJndiLayout);
        pnlJndiLayout.setHorizontalGroup(
            pnlJndiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJndiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJndiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJndi, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDescriptionImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlJndiLayout.createSequentialGroup()
                        .addGroup(pnlJndiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblJndiDesctiption)
                            .addComponent(jLabel1))
                        .addGap(0, 13, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlJndiLayout.setVerticalGroup(
            pnlJndiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJndiLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtJndi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblJndiDesctiption, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDescriptionImage, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(pnlJndi, "card4");
    }// </editor-fold>//GEN-END:initComponents

    private void txtUrlSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUrlSampleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUrlSampleActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDriver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDescriptionImage;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblJndiDesctiption;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUrl;
    private javax.swing.JLabel lblUrlSample;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel pnlJdbc;
    private javax.swing.JPanel pnlJndi;
    private javax.swing.JTextField txtJndi;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUrl;
    private javax.swing.JTextField txtUrlSample;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
