package com.jhappy.mybateans.wizard.configxml;

import com.jhappy.mybateans.wizard.mapperxml.*;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

public final class MyBatisConfigXmlVisualPanel extends JPanel {

    /**
     * Creates new form MyBatisMapperXmlVisualPanel1
     */
    public MyBatisConfigXmlVisualPanel() {
        initComponents();

    }

    @Override
    public String getName() {
        return "Step #1";
    }

    public String getDataSourceType() {
        return (String) cmbDataSourceType.getSelectedItem();
    }

    public String getTManagerType() {
        return (String) cmbTManagerType.getSelectedItem();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDataSourceType = new javax.swing.JLabel();
        lblTmanagerType = new javax.swing.JLabel();
        cmbTManagerType = new javax.swing.JComboBox<>();
        cmbDataSourceType = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDataSourceDescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaTManagerTypeDesctiption = new javax.swing.JTextArea();

        lblDataSourceType.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblDataSourceType, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel.class, "MyBatisConfigXmlVisualPanel.lblDataSourceType.text")); // NOI18N
        lblDataSourceType.setToolTipText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel.class, "MyBatisConfigXmlVisualPanel.lblDataSourceType.toolTipText")); // NOI18N

        lblTmanagerType.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(lblTmanagerType, org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel.class, "MyBatisConfigXmlVisualPanel.lblTmanagerType.text")); // NOI18N

        cmbTManagerType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JDBC", "MANAGED" }));

        cmbDataSourceType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "POOLED", "UNPOOLED", "JNDI" }));

        txtaDataSourceDescription.setEditable(false);
        txtaDataSourceDescription.setColumns(20);
        txtaDataSourceDescription.setRows(5);
        txtaDataSourceDescription.setText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel.class, "MyBatisConfigXmlVisualPanel.txtaDataSourceDescription.text")); // NOI18N
        jScrollPane1.setViewportView(txtaDataSourceDescription);

        txtaTManagerTypeDesctiption.setEditable(false);
        txtaTManagerTypeDesctiption.setColumns(20);
        txtaTManagerTypeDesctiption.setRows(5);
        txtaTManagerTypeDesctiption.setText(org.openide.util.NbBundle.getMessage(MyBatisConfigXmlVisualPanel.class, "MyBatisConfigXmlVisualPanel.txtaTManagerTypeDesctiption.text")); // NOI18N
        jScrollPane2.setViewportView(txtaTManagerTypeDesctiption);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbDataSourceType, 0, 455, Short.MAX_VALUE)
                    .addComponent(cmbTManagerType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDataSourceType)
                            .addComponent(lblTmanagerType))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTmanagerType)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbTManagerType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDataSourceType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbDataSourceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDataSourceType;
    private javax.swing.JComboBox<String> cmbTManagerType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDataSourceType;
    private javax.swing.JLabel lblTmanagerType;
    private javax.swing.JTextArea txtaDataSourceDescription;
    private javax.swing.JTextArea txtaTManagerTypeDesctiption;
    // End of variables declaration//GEN-END:variables
}
