<#ftl strip_whitespace=false>
package ${packageName};

import java.util.List;
import org.apache.ibatis.annotations.Mapper;

/**
 * Mapper interface for ${tableName}.
 * Generated by MyBateans.
 */
@Mapper
public interface ${className}Mapper {

    /**
     * @param ${variableName}
     * @return 
     */
    List<${className}> select(${className} ${variableName});

    /**
     * @param ${variableName}
     * @return 
     */
    int insert(${className} ${variableName});

    /**
     * @param ${variableName}
     * @return 
     */
    int update(${className} ${variableName});

    /**
     * @param ${variableName}
     * @return 
     */
    int delete(${className} ${variableName});

}